import { PersistentClinicalProfile } from './clinicalMemoryStore';
import { Medication, Profile } from '@/types';

export interface ChatMessage {
  id: string;
  sender: 'user' | 'assistant';
  text: string;
  timestamp: string;
}

export class GeminiClinicalService {
  /**
   * Retrieves the Gemini API key from localStorage, import.meta.env, or fallback
   */
  static getApiKey(): string {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem('syncura_gemini_api_key');
      if (stored && stored.trim()) return stored.trim();
    }
    return (import.meta.env.VITE_GEMINI_API_KEY || '').trim();
  }

  static setApiKey(key: string): void {
    if (typeof window !== 'undefined') {
      localStorage.setItem('syncura_gemini_api_key', key.trim());
    }
  }

  /**
   * Generates a clinically sound, personalized response using Google Gemini 1.5 Flash
   */
  static async askClinicalAdvocate(
    userPrompt: string,
    profile: Profile,
    medications: Medication[],
    memory: PersistentClinicalProfile
  ): Promise<string> {
    const activeMedsSummary = medications
      .filter((m) => m.profile_id === profile.id && m.is_active)
      .map((m) => `- ${m.name} ${m.dosage_strength} (${m.instructions}) [Refills: ${m.remaining_refills}]`)
      .join('\n');

    const allergiesSummary = (profile.allergies || []).join(', ') || 'No known drug allergies';

    const diagnosesSummary = memory.chronic_diagnoses
      .map((d) => `- ${d.condition} (Diagnosed ${d.diagnosed_year}): ${d.notes}`)
      .join('\n');

    const contraindicationsSummary = memory.permanent_drug_contraindications
      .map((c) => `- ${c.drug_or_class}: ${c.adverse_reaction} -> ${c.rule}`)
      .join('\n');

    const labTrendsSummary = memory.lab_trajectories
      .map((t) => `- ${t.test_name}: ${t.history.map((h) => `${h.date}: ${h.value}${t.unit}`).join(' -> ')} (${t.trajectory_summary})`)
      .join('\n');

    const systemInstruction = `You are "Syncura AI", a compassionate, highly knowledgeable, board-certified clinical pharmacist and personal health advocate for seniors and family caregivers.
Your goal is to provide clear, reassuring, plain-English answers to medical, medication, food-interaction, and lab-related questions.

PATIENT CLINICAL CONTEXT:
- Name: ${profile.name} (Age: 74, Female)
- Known Allergies: ${allergiesSummary}
- Active Prescriptions:
${activeMedsSummary}
- Chronic Diagnoses:
${diagnosesSummary}
- Permanent Contraindications:
${contraindicationsSummary}
- Lab Trajectories:
${labTrendsSummary}

GUIDELINES:
1. Speak with warmth, clarity, and empathy. Avoid dense medical jargon; explain concepts simply for aging seniors and adult children.
2. Cross-reference the patient's exact active medications, allergies, and permanent contraindications before advising.
3. If an over-the-counter medication or supplement poses an interaction (e.g. Advil/NSAIDs with Eliquis/Blood thinners, or Penicillin cross-reactivity), call it out clearly and recommend safer alternatives (like Acetaminophen for pain).
4. For lab results, explain what the numbers mean relative to normal ranges.
5. Always remind them that you are an AI clinical advocate and to consult their physician (Dr. Robert Chen) for formal medical orders.`;

    const key = this.getApiKey();

    if (!key) {
      console.warn('Gemini API key not found in env or localStorage. Falling back to local clinical engine.');
      return this.getLocalClinicalFallback(userPrompt, profile);
    }

    try {
      const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${key}`;

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              role: 'user',
              parts: [{ text: `${systemInstruction}\n\nUSER QUESTION: ${userPrompt}` }],
            },
          ],
          generationConfig: {
            temperature: 0.3,
            maxOutputTokens: 700,
          },
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        console.warn('Gemini API error:', errorData);
        throw new Error(`Gemini API returned status ${response.status}: ${JSON.stringify(errorData)}`);
      }

      const data = await response.json();
      const answer = data.candidates?.[0]?.content?.parts?.[0]?.text;

      if (!answer) {
        throw new Error('No text generated by Gemini.');
      }

      return answer.trim();
    } catch (err: any) {
      console.warn('Gemini live request failed. Using local clinical fallback:', err.message);
      return this.getLocalClinicalFallback(userPrompt, profile);
    }
  }

  private static getLocalClinicalFallback(userPrompt: string, profile: Profile): string {
    const promptLower = userPrompt.toLowerCase();

    if (promptLower.includes('tylenol') || promptLower.includes('advil') || promptLower.includes('pain') || promptLower.includes('headache')) {
      return `For ${profile.name.split(' ')[0]}, **Acetaminophen (Tylenol Extra Strength)** is the safest pain reliever because she is taking **Apixaban (Eliquis)**.

⚠️ **Important Warning:** Do **NOT** take NSAIDs like Advil (Ibuprofen), Aleve (Naproxen), or Aspirin, because combining NSAIDs with blood thinners significantly increases stomach bleeding risk. Stick to Tylenol (up to 4,000 mg daily maximum) and ensure at least 6 hours between doses.`;
    }

    if (promptLower.includes('coffee') || promptLower.includes('breakfast') || promptLower.includes('thyroid') || promptLower.includes('levothyroxine')) {
      return `**Levothyroxine (Thyroid):** Take it first thing in the morning with a full glass of plain water on an empty stomach. 

☕ Wait at least **30 to 60 minutes** before having your morning coffee, tea, or breakfast. Coffee and calcium bind to the medication in the stomach and reduce its absorption by more than 50%.`;
    }

    if (promptLower.includes('lisinopril') || promptLower.includes('cough')) {
      return `**Lisinopril Advisory:** 
Eleanor's persistent clinical records note that Lisinopril was **discontinued in 2021 due to a severe dry cough**. 

⚠️ **Do NOT restart Lisinopril or ACE inhibitors.** If blood pressure adjustment is needed, her doctor (Dr. Robert Chen) recommends ARB or Calcium Channel Blocker alternatives. Regarding coffee with blood pressure medications, avoid excessive caffeine as it causes temporary blood pressure spikes.`;
    }

    if (promptLower.includes('lab') || promptLower.includes('a1c') || promptLower.includes('quest') || promptLower.includes('kidney')) {
      return `**Quest Diagnostics Metabolic Panel Summary for Eleanor:**

1. **HbA1c (6.8%):** Excellent! Your blood sugar control has improved steadily (down from 7.4% last year) and is safely below the 7.0% goal under Metformin.
2. **eGFR Kidney Function (64 mL/min):** Stable and normal for your age. This confirms your kidneys are clearing your medications safely.
3. **Potassium (4.4 mmol/L):** Perfectly in the safe middle range (3.5 – 5.0).`;
    }

    return `Based on Eleanor's active records (Apixaban, Metformin, Levothyroxine, and Penicillin allergy), everything is currently balanced and safe. 

If you have a specific question regarding a new symptom, pill timing, or doctor appointment questions, feel free to ask! Always consult Dr. Robert Chen before starting any new over-the-counter supplements.`;
  }
}
